name: Compile, Test & Deploy Badge NFT

on:
  push:
    branches:
      - main
      - feature/badge-nft

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Scarb (Cairo package manager)
        run: |
          curl -L https://install.scarb.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up Python & Starkli CLI
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install starknet-devnet

      - name: Build contract
        run: scarb build

      - name: Deploy contract to StarkNet Testnet
        env:
          STARKNET_PRIVATE_KEY: ${{ secrets.STARKNET_PRIVATE_KEY }}
        run: |
          echo "🚀 Deploy step would be run here with Starkli or a deployment script."
          echo "Private key and ABI available. Consider using starkli or Python script."
